output solid_bsp_door.vvm
materialprefix models/indoor/old_couche_001/old_couche_001.mat
 
origin 0 0 0
rotate 0 0 0
scale 1

scene "iqe/tpose.iqe" noanim 1
scene "iqe/open_front.iqe" nomesh 1 name "open_front" fps 30
scene "iqe/close_front.iqe" nomesh 1 name "close_front" fps 30
scene "iqe/open_back.iqe" nomesh 1 name "open_back" fps 30
scene "iqe/close_back.iqe" nomesh 1 name "close_back" fps 30
