output player.vvm
materialprefix /models/characters/player/

scene "iqe/tpose.iqe"

origin 0 0 0
rotate 0 -90 0

scene "iqe/idle_breathing.iqe" name "idle_breathing" fps 30
scene "iqe/idle_dizzy.iqe" name "idle_dizzy" fps 30
scene "iqe/idle_injured_yellow.iqe" name "idle_injured_yellow" fps 30
scene "iqe/idle_injured_orange.iqe" name "idle_injured_orange" fps 30
scene "iqe/idle_injured_red.iqe" name "idle_injured_red" fps 30