all:
	make menu
	make games
	make plugins

menu-valve:
	cd menu-fn && $(MAKE)

menu:
	cd menu-vgui && $(MAKE)

games:
	cd client/schizomania && $(MAKE)
	cd server/schizomania && $(MAKE)

plugins:
	cd plugins && $(MAKE)
